### ISSUE TITLE
example2里的例子和README里不一样

### ISSUE THREAD

**Issue by zhangchunlin** [andelf/PyAIML#1]
~/oss/PyAIML/example2$ python simple.py 
Loading cn-startup.xml... done (0.02 seconds)
Loading cn-test.aiml... done (0.00 seconds)

> 你好
> 你现在在什么地方?
> 厦门
> 真希望我也在厦门, 陪你.
> 北京
> 我暂时不会说别的了.
> 真的吗?
> 我暂时不会说别的了.
> 太好了
> 我暂时不会说别的了.
> 谢谢
> 我暂时不会说别的了.
> 你好
> 我暂时不会说别的了.
> exit
> 我暂时不会说别的了.

**Comment by sunzejian** [comment]
活动代码页: 936

D:\python\example2>python simple.py
Loading cn-startup.xml... done (0.02 seconds)
Loading cn-test.aiml... done (0.00 seconds)
> 再见
浣犵幇鍦ㄥ湪浠€涔堝湴鏂?
> 谢谢
鐪熷笇鏈涙垜涔熷湪袥谢, 闄綘.
> hello
鎴戞殏鏃朵笉浼氳鍒殑浜?

老师，我在cmd里面测试了一下，老是出来乱码，将cmd切换到utf-8（chcp 65001）之后程序无法执行，像下面这样
Active code page: 65001

D:\python\example2>python simple.py
Loading cn-startup.xml... done (0.02 seconds)
Traceback (most recent call last):
  File "simple.py", line 22, in <module>
    k.respond("load aiml cnask")
  File "../aiml\Kernel.py", line 343, in respond
    response = self._respond(s, sessionID)
  File "../aiml\Kernel.py", line 407, in _respond
    response += self._processElement(elem, sessionID).strip()
  File "../aiml\Kernel.py", line 438, in _processElement
    return handlerFunc(elem, sessionID)
  File "../aiml\Kernel.py", line 947, in _processTemplate
    response += self._processElement(e, sessionID)
  File "../aiml\Kernel.py", line 438, in _processElement
    return handlerFunc(elem, sessionID)
  File "../aiml\Kernel.py", line 692, in _processLearn
    self.learn(filename)
  File "../aiml\Kernel.py", line 294, in learn
    if self._verboseMode: print "Loading %s..." % f,
LookupError: unknown encoding: cp65001

D:\python\example2>

请问可能出错在哪里啊

**Comment by andelf** [comment]
编码耶。。。就是编码错了
